AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  coffee-sam

Globals:
  Function:
    Timeout: 3

Resources:
  GetShopsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-shops/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoCoffeeShopsTable
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref DynamoCoffeeShopsTable
      Events:
        GetShops:
          Type: Api
          Properties:
            Path: /shops
            Method: get

  PostShopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/post-shop/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoCoffeeShopsTable
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoCoffeeShopsTable
      Events:
        GetShops:
          Type: Api
          Properties:
            Path: /shops
            Method: post

  TriggerDeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/trigger-deploy/
      Handler: app.handler
      Runtime: nodejs12.x

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: TriggerDeploySNS
      TopicName: TriggerDeployTopic
      Subscription:
        - Endpoint: !GetAtt
            - TriggerDeployFunction
            - Arn
          Protocol: lambda

  DynamoCoffeeShopsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: coffee-table
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TriggerDeployInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref TriggerDeployFunction
      Principal: sns.amazonaws.com

  TriggerDeployTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sns:Publish'
            Resource: !Ref SNSTopic
            Principal:
              AWS: '*'
            Condition:
              ArnEquals:
                AWS:SourceArn: !Ref PostShopFunction
