version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coffee-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-enia2tim3oz7"
s3_prefix = "coffee-sam"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

