AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  coffee-sam

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GetShopsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-shops/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoCoffeeShopsTable
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref DynamoCoffeeShopsTable
      Events:
        GetShops:
          Type: Api
          Properties:
            Path: /shops
            Method: get

  PostShopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/post-shop/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoCoffeeShopsTable
          SNS_TOPIC_ARN: !Ref TriggerDeploySNS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoCoffeeShopsTable
        - SNSCrudPolicy:
            TopicName: !GetAtt TriggerDeploySNS.TopicName
      Events:
        GetShops:
          Type: Api
          Properties:
            Path: /shops
            Method: post

  TriggerDeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/trigger-deploy/
      Handler: app.handler
      Runtime: nodejs12.x

  TriggerDeploySNS:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt
            - TriggerDeployFunction
            - Arn
          Protocol: lambda

  DynamoCoffeeShopsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: coffee-table
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TriggerDeployInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref TriggerDeployFunction
      Principal: sns.amazonaws.com
